import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'

// Clean old caches from previous builds
cleanupOutdatedCaches()

// Precache all assets generated by the Vite build
precacheAndRoute(self.__WB_MANIFEST)

// ─── Prompt-mode update: wait for user to confirm ───
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// ─── Show system notification when a NEW version is installed ───
// This fires even when the app is backgrounded on mobile
self.addEventListener('install', (event) => {
  // Only notify on updates, not the very first install
  if (self.registration.active) {
    event.waitUntil(
      (async () => {
        if (Notification.permission === 'granted') {
          try {
            await self.registration.showNotification('EleFam Update Available 🎉', {
              body: 'A new version is ready! Tap to open and update.',
              icon: '/icons/wallets/EF-logo.png',
              badge: '/icons/wallets/EF-logo.png',
              tag: 'elefam-update',
              renotify: true,
              vibrate: [200, 100, 200],
              data: { type: 'sw-update' },
            })
          } catch (err) {
            console.error('SW: Failed to show update notification:', err)
          }
        }
      })()
    )
  }
})

// ─── Handle notification tap: focus or open the app ───
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Focus an existing window if one is open
        for (const client of clientList) {
          if ('focus' in client) {
            return client.focus()
          }
        }
        // Otherwise open a fresh window
        return self.clients.openWindow('/')
      })
  )
})
