import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'

// Clean old caches from previous builds
cleanupOutdatedCaches()

// Precache all assets generated by the Vite build
precacheAndRoute(self.__WB_MANIFEST)

// ─── Prompt-mode update: wait for user to confirm ───
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
